# Generated by Django 5.2.8 on 2025-12-08 06:56

import apps.campaigns.constants
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_name", models.CharField(max_length=255, unique=True)),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Tenant-specific template if set.",
                        null=True,
                    ),
                ),
                (
                    "sms_body",
                    models.CharField(
                        help_text="Use {{variable_name}} for dynamic content.",
                        max_length=160,
                    ),
                ),
                (
                    "recipient_numbers_list",
                    models.TextField(
                        blank=True, help_text="Comma-separated phone numbers."
                    ),
                ),
                (
                    "supports_whatsapp",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template can be used for WhatsApp",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactList",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "double_opt_in",
                    models.BooleanField(
                        default=False,
                        help_text="Require email confirmation before adding contacts",
                    ),
                ),
                ("total_contacts", models.PositiveIntegerField(default=0)),
                ("active_contacts", models.PositiveIntegerField(default=0)),
                ("unsubscribed_contacts", models.PositiveIntegerField(default=0)),
                ("bounced_contacts", models.PositiveIntegerField(default=0)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_lists",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact List",
                "verbose_name_plural": "Contact Lists",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("UNSUBSCRIBED", "Unsubscribed"),
                            ("BOUNCED", "Bounced"),
                            ("COMPLAINED", "Complained"),
                            ("PENDING", "Pending Verification"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        editable=False,
                        help_text="Unique token for unsubscribe links",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="For double opt-in", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("CSV_IMPORT", "CSV Import"),
                            ("JSON_IMPORT", "JSON Import"),
                            ("API", "API"),
                            ("SIGNUP_FORM", "Signup Form"),
                            ("MIGRATION", "Migration"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "source_details",
                    models.JSONField(
                        blank=True,
                        help_text="Additional details about the source (e.g., import file name)",
                        null=True,
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, help_text="Custom contact attributes"
                    ),
                ),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("emails_opened", models.PositiveIntegerField(default=0)),
                ("emails_clicked", models.PositiveIntegerField(default=0)),
                ("last_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_email_opened_at", models.DateTimeField(blank=True, null=True)),
                ("last_email_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("bounce_count", models.PositiveIntegerField(default=0)),
                ("complaint_count", models.PositiveIntegerField(default=0)),
                ("last_bounce_at", models.DateTimeField(blank=True, null=True)),
                ("last_complaint_at", models.DateTimeField(blank=True, null=True)),
                ("bounce_reason", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for segmentation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="authentication.organization",
                    ),
                ),
                (
                    "lists",
                    models.ManyToManyField(
                        blank=True, related_name="contacts", to="campaigns.contactlist"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=255)),
                (
                    "preview_text",
                    models.CharField(
                        blank=True,
                        help_text="Preview text shown in email clients",
                        max_length=255,
                    ),
                ),
                ("html_content", models.TextField(help_text="HTML email body")),
                (
                    "text_content",
                    models.TextField(blank=True, help_text="Plain text fallback"),
                ),
                ("from_name", models.CharField(max_length=100)),
                ("from_email", models.EmailField(max_length=254)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("PAUSED", "Paused"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to send the campaign (stored in UTC)",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("stats_total_recipients", models.PositiveIntegerField(default=0)),
                ("stats_sent", models.PositiveIntegerField(default=0)),
                ("stats_delivered", models.PositiveIntegerField(default=0)),
                ("stats_opened", models.PositiveIntegerField(default=0)),
                ("stats_clicked", models.PositiveIntegerField(default=0)),
                ("stats_bounced", models.PositiveIntegerField(default=0)),
                ("stats_complained", models.PositiveIntegerField(default=0)),
                ("stats_unsubscribed", models.PositiveIntegerField(default=0)),
                ("stats_failed", models.PositiveIntegerField(default=0)),
                ("stats_unique_opens", models.PositiveIntegerField(default=0)),
                ("stats_unique_clicks", models.PositiveIntegerField(default=0)),
                ("stats_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        default=100, help_text="Number of emails to send per batch"
                    ),
                ),
                (
                    "batch_delay_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Delay between batches in seconds"
                    ),
                ),
                ("track_opens", models.BooleanField(default=True)),
                ("track_clicks", models.BooleanField(default=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "segment_filters",
                    models.JSONField(
                        blank=True,
                        help_text="Additional filters for contact selection",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="authentication.organization",
                    ),
                ),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "contact_lists",
                    models.ManyToManyField(
                        blank=True, related_name="campaigns", to="campaigns.contactlist"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("automation_name", models.CharField(max_length=100)),
                (
                    "reason_name",
                    models.CharField(
                        choices=[
                            ("EMAIL_VERIFICATION", "Email Verification"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("WELCOME_EMAIL", "Welcome Email"),
                            ("CAMPAIGN_LAUNCH", "Campaign Launch"),
                            ("CAMPAIGN_REMINDER", "Campaign Reminder"),
                            ("CAMPAIGN_FOLLOWUP", "Campaign Follow-up"),
                            ("SUBSCRIPTION_CONFIRMATION", "Subscription Confirmation"),
                            ("SUBSCRIPTION_RENEWAL", "Subscription Renewal"),
                            ("SUBSCRIPTION_EXPIRING", "Subscription Expiring"),
                            ("INVITATION_SENT", "Invitation Sent"),
                            ("INVITATION_REMINDER", "Invitation Reminder"),
                            ("MEMBER_ONBOARDING", "Member Onboarding"),
                            ("OTHER", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("action_name", models.CharField(blank=True, max_length=100)),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("PUSH", "Push Notification"),
                        ],
                        default="EMAIL",
                        max_length=10,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the automation rule.",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("DELAY", "Delay"),
                            ("SCHEDULE", "Schedule"),
                        ],
                        default="IMMEDIATE",
                        max_length=20,
                    ),
                ),
                (
                    "delay_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Amount of time to delay. (e.g., 5, 10, 20)",
                        null=True,
                    ),
                ),
                (
                    "delay_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SECONDS", "Seconds"),
                            ("MINUTES", "Minutes"),
                            ("HOURS", "Hours"),
                            ("DAYS", "Days"),
                        ],
                        help_text="Unit of time for the delay (e.g., SECONDS, MINUTES, etc.).",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INTERVAL", "Interval"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        help_text="Frequency of the schedule (e.g., INTERVAL, DAILY, WEEKLY, MONTHLY).",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "schedule_interval_amount",
                    models.PositiveIntegerField(
                        blank=True, help_text="e.g., every '5' minutes", null=True
                    ),
                ),
                (
                    "schedule_interval_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SECONDS", "Seconds"),
                            ("MINUTES", "Minutes"),
                            ("HOURS", "Hours"),
                            ("DAYS", "Days"),
                        ],
                        help_text="e.g., every 5 'minutes'",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "schedule_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time of day to send (UTC). e.g., 2:30 PM UTC",
                        null=True,
                    ),
                ),
                (
                    "schedule_day_of_week",
                    models.PositiveIntegerField(
                        blank=True, help_text="1=Monday, 7=Sunday", null=True
                    ),
                ),
                (
                    "schedule_day_of_month",
                    models.PositiveIntegerField(
                        blank=True, help_text="1-31", null=True
                    ),
                ),
                (
                    "num_occurrences",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of times to execute the scheduled task. Leave blank for indefinite.",
                        null=True,
                    ),
                ),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("retry_delay_minutes", models.PositiveIntegerField(default=5)),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of emails to process in one batch"
                    ),
                ),
                (
                    "filter_conditions",
                    models.JSONField(
                        blank=True,
                        help_text="JSON conditions for advanced filtering. Example: {'status': 'active', 'tags': ['premium']}",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=5, help_text="1=highest priority, 10=lowest priority"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this rule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="authentication.organization",
                    ),
                ),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campaign to launch when this rule triggers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_rules",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "contact_list",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contact list to target when this rule triggers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_rules",
                        to="campaigns.contactlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automation Rule",
                "verbose_name_plural": "Automation Rules",
            },
        ),
        migrations.CreateModel(
            name="EmailDeliveryLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_name",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of automation reason at send time",
                        max_length=100,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of trigger type at send time",
                        max_length=20,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("sender_email", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("BOUNCED", "Bounced"),
                            ("COMPLAINED", "Complained"),
                            ("OPENED", "Opened"),
                            ("CLICKED", "Clicked"),
                            ("UNSUBSCRIBED", "Unsubscribed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("planned_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("unique_click_count", models.PositiveIntegerField(default=0)),
                (
                    "bounce_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HARD", "Hard Bounce"),
                            ("SOFT", "Soft Bounce"),
                            ("COMPLAINT", "Complaint"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bounce_reason", models.TextField(blank=True)),
                ("spam_score", models.FloatField(blank=True, null=True)),
                ("is_spam", models.BooleanField(default=False)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent for opens/clicks"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "event_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Chronological list of provider events",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Template variables used for rendering",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error information for failed sends"
                    ),
                ),
                (
                    "automation_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.automationrule",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_logs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_logs",
                        to="campaigns.contact",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="campaigns.emaildeliverylog",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_delivery_logs",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Delivery Log",
                "verbose_name_plural": "Email Delivery Logs",
            },
        ),
        migrations.CreateModel(
            name="EmailAction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("RESEND", "Resend"),
                            ("FORWARD", "Forward"),
                            ("CANCEL", "Cancel"),
                            ("ARCHIVE", "Archive"),
                            ("SUPPRESS", "Suppress"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_recipient",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.UUIDField(
                        blank=True,
                        help_text="User ID who performed the action",
                        null=True,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "new_delivery_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_actions",
                        to="campaigns.emaildeliverylog",
                    ),
                ),
                (
                    "original_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="campaigns.emaildeliverylog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Action",
                "verbose_name_plural": "Email Actions",
            },
        ),
        migrations.CreateModel(
            name="EmailProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("AWS_SES", "Amazon SES"),
                            ("SENDGRID", "SendGrid"),
                            ("BREVO", "Brevo (formerly Sendinblue)"),
                            ("SMTP", "Custom SMTP"),
                            ("INTERNAL", "Internal System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a shared platform provider accessible by all organizations",
                    ),
                ),
                (
                    "encrypted_config",
                    models.TextField(
                        help_text="Encrypted provider-specific configuration"
                    ),
                ),
                ("max_emails_per_minute", models.PositiveIntegerField(default=100)),
                ("max_emails_per_hour", models.PositiveIntegerField(default=1000)),
                ("max_emails_per_day", models.PositiveIntegerField(default=10000)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1, help_text="Lower number = higher priority"
                    ),
                ),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("DEGRADED", "Degraded"),
                            ("UNHEALTHY", "Unhealthy"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("health_details", models.TextField(blank=True)),
                ("emails_sent_today", models.PositiveIntegerField(default=0)),
                ("emails_sent_this_hour", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that owns this provider (null for shared providers)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_providers",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Provider",
                "verbose_name_plural": "Email Providers",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="emaildeliverylog",
            name="email_provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.emailprovider",
            ),
        ),
        migrations.CreateModel(
            name="EmailQueue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True)),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        help_text="Template variables and context",
                        null=True,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, help_text="Custom email headers", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("RETRYING", "Retrying"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=5, help_text="1=highest, 10=lowest"
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                (
                    "assigned_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.emailprovider",
                    ),
                ),
                (
                    "automation_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_emails",
                        to="campaigns.automationrule",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_emails",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queued_emails",
                        to="campaigns.contact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_queue_items",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Queue Item",
                "verbose_name_plural": "Email Queue",
                "ordering": ["priority", "scheduled_at"],
            },
        ),
        migrations.AddField(
            model_name="emaildeliverylog",
            name="queue_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_log",
                to="campaigns.emailqueue",
            ),
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EMAIL_VERIFICATION", "Email Verification"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("WELCOME", "Welcome"),
                            ("NEWSLETTER", "Newsletter"),
                            ("PROMOTIONAL", "Promotional"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("INVITATION", "Invitation"),
                            ("REMINDER", "Reminder"),
                            ("NOTIFICATION", "Notification"),
                            ("SUBSCRIPTION_CONFIRMATION", "Subscription Confirmation"),
                            ("SUBSCRIPTION_RENEWAL", "Subscription Renewal"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Template category for organization",
                        max_length=100,
                    ),
                ),
                ("email_subject", models.CharField(max_length=255)),
                (
                    "preview_text",
                    models.CharField(
                        blank=True,
                        help_text="Preview text shown in email clients",
                        max_length=255,
                    ),
                ),
                (
                    "email_body",
                    models.TextField(
                        help_text="Use {{variable_name}} for dynamic content."
                    ),
                ),
                (
                    "text_body",
                    models.TextField(
                        blank=True, help_text="Plain text fallback content."
                    ),
                ),
                ("default_from_name", models.CharField(blank=True, max_length=100)),
                ("default_from_email", models.EmailField(blank=True, max_length=254)),
                ("default_reply_to", models.EmailField(blank=True, max_length=254)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal description of this template"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for organizing templates",
                    ),
                ),
                (
                    "variable_schema",
                    models.JSONField(
                        blank=True,
                        help_text="JSON schema describing available variables. Example: {'first_name': 'string', 'company': 'string'}",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.AddField(
            model_name="emaildeliverylog",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_rules",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.CreateModel(
            name="EmailValidation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("is_valid_format", models.BooleanField(default=True)),
                ("is_disposable", models.BooleanField(default=False)),
                (
                    "is_role_based",
                    models.BooleanField(
                        default=False, help_text="info@, admin@, support@, etc."
                    ),
                ),
                ("domain_mx_valid", models.BooleanField(default=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("RISKY", "Risky"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                (
                    "validation_score",
                    models.FloatField(
                        blank=True, help_text="Validation score 0-100", null=True
                    ),
                ),
                ("bounce_count", models.PositiveIntegerField(default=0)),
                ("complaint_count", models.PositiveIntegerField(default=0)),
                ("successful_deliveries", models.PositiveIntegerField(default=0)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("blacklist_reason", models.TextField(blank=True)),
                ("blacklisted_at", models.DateTimeField(blank=True, null=True)),
                ("last_validated_at", models.DateTimeField(auto_now=True)),
                (
                    "validation_provider",
                    models.CharField(
                        blank=True,
                        help_text="Service used for validation",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Validation",
                "verbose_name_plural": "Email Validations",
                "indexes": [
                    models.Index(
                        fields=["email_address"], name="campaigns_e_email_a_3a067e_idx"
                    ),
                    models.Index(
                        fields=["validation_status", "is_blacklisted"],
                        name="campaigns_e_validat_e2f451_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="emaildeliverylog",
            name="email_validation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="campaigns.emailvalidation",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationEmailConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Organization timezone for campaign scheduling",
                        max_length=50,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("BASIC", "Basic"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                (
                    "plan_limits",
                    models.JSONField(
                        default=apps.campaigns.constants.get_default_plan_limits_json,
                        help_text="Plan limits including batch_size, api_requests_per_minute, etc.",
                    ),
                ),
                ("emails_per_day", models.PositiveIntegerField(default=100)),
                ("emails_per_month", models.PositiveIntegerField(default=1000)),
                ("emails_per_minute", models.PositiveIntegerField(default=10)),
                (
                    "default_from_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "custom_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("custom_domain_verified", models.BooleanField(default=False)),
                (
                    "domain_verification_token",
                    models.CharField(blank=True, max_length=255),
                ),
                ("emails_sent_today", models.PositiveIntegerField(default=0)),
                ("emails_sent_this_month", models.PositiveIntegerField(default=0)),
                ("last_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_daily_reset", models.DateField(blank=True, null=True)),
                ("last_monthly_reset", models.DateField(blank=True, null=True)),
                ("api_requests_today", models.PositiveIntegerField(default=0)),
                ("last_api_request_at", models.DateTimeField(blank=True, null=True)),
                ("is_suspended", models.BooleanField(default=False)),
                ("suspension_reason", models.TextField(blank=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bounce_rate",
                    models.FloatField(default=0.0, help_text="Bounce rate percentage"),
                ),
                (
                    "complaint_rate",
                    models.FloatField(
                        default=0.0, help_text="Complaint rate percentage"
                    ),
                ),
                (
                    "reputation_score",
                    models.FloatField(
                        default=100.0, help_text="Email reputation score (0-100)"
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_configuration",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Email Configuration",
                "verbose_name_plural": "Organization Email Configurations",
            },
        ),
        migrations.AddField(
            model_name="automationrule",
            name="email_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_rules",
                to="campaigns.organizationemailconfiguration",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationEmailProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary provider for this organization",
                    ),
                ),
                (
                    "custom_encrypted_config",
                    models.TextField(
                        blank=True, help_text="Organization-specific config overrides"
                    ),
                ),
                (
                    "custom_max_emails_per_minute",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "custom_max_emails_per_hour",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "custom_max_emails_per_day",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("emails_sent_today", models.PositiveIntegerField(default=0)),
                ("emails_sent_this_hour", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("bounce_rate", models.FloatField(default=0.0)),
                ("complaint_rate", models.FloatField(default=0.0)),
                ("delivery_rate", models.FloatField(default=100.0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_configs",
                        to="authentication.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_configs",
                        to="campaigns.emailprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Email Provider",
                "verbose_name_plural": "Organization Email Providers",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="email_provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific provider to use (defaults to organization primary)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="campaigns.organizationemailprovider",
            ),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="email_provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization-specific provider configuration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation_rules",
                to="campaigns.organizationemailprovider",
            ),
        ),
        migrations.CreateModel(
            name="SMSConfigurationModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_or_type",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "endpoint_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_ssid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("auth_token", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "verified_service_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_from_number",
                    models.CharField(
                        blank=True,
                        help_text="Twilio phone number to use as sender (e.g. +15551234567)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "whatsapp_from_number",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp Business number (e.g. whatsapp:+15551234567)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable WhatsApp messaging for this configuration",
                    ),
                ),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SMS/WhatsApp Configurations",
            },
        ),
        migrations.AddField(
            model_name="automationrule",
            name="sms_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_rules",
                to="campaigns.smsconfigurationmodel",
            ),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="sms_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_rules",
                to="campaigns.smstemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="contactlist",
            index=models.Index(
                fields=["organization", "name"], name="campaigns_c_organiz_2a1008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactlist",
            index=models.Index(
                fields=["organization", "is_active"],
                name="campaigns_c_organiz_bd6870_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contactlist",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["organization", "email"], name="campaigns_c_organiz_73562c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["organization", "status"], name="campaigns_c_organiz_746894_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["organization", "is_active", "status"],
                name="campaigns_c_organiz_832f15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["unsubscribe_token"], name="campaigns_c_unsubsc_e2495c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["organization", "source"], name="campaigns_c_organiz_73a9cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("organization", "email")},
        ),
        migrations.AddIndex(
            model_name="emailaction",
            index=models.Index(
                fields=["original_log", "action_type"],
                name="campaigns_e_origina_7546fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailaction",
            index=models.Index(
                fields=["performed_at", "action_type"],
                name="campaigns_e_perform_063470_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailprovider",
            index=models.Index(
                fields=["organization", "is_active"],
                name="campaigns_e_organiz_2491c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailprovider",
            index=models.Index(
                fields=["is_shared", "is_default"],
                name="campaigns_e_is_shar_d0d35f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailprovider",
            index=models.Index(
                fields=["provider_type", "is_active"],
                name="campaigns_e_provide_48ce5b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailprovider",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("name", "organization"),
                name="unique_provider_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailprovider",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_shared", True), ("organization__isnull", True)),
                fields=("name",),
                name="unique_shared_provider_name",
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["organization", "status"], name="campaigns_e_organiz_b2e2c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["campaign", "status"], name="campaigns_e_campaig_5cd02a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                fields=["scheduled_at", "priority"],
                name="campaigns_e_schedul_99d1c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["organization", "category"],
                name="campaigns_e_organiz_393b92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["organization", "is_active"],
                name="campaigns_e_organiz_653573_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("organization", "template_name"),
                name="unique_template_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["organization", "delivery_status"],
                name="campaigns_e_organiz_b4bd4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["organization", "sent_at"],
                name="campaigns_e_organiz_6b8ad3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["campaign", "delivery_status"],
                name="campaigns_e_campaig_013f40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["campaign", "sent_at"], name="campaigns_e_campaig_b00a39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["recipient_email", "sent_at"],
                name="campaigns_e_recipie_73e4f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["delivery_status", "sent_at"],
                name="campaigns_e_deliver_68bd4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliverylog",
            index=models.Index(
                fields=["provider_message_id"], name="campaigns_e_provide_095efb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationemailconfiguration",
            index=models.Index(
                fields=["organization"], name="campaigns_o_organiz_4acfdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationemailconfiguration",
            index=models.Index(
                fields=["plan_type", "is_active"], name="campaigns_o_plan_ty_84bbfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationemailprovider",
            index=models.Index(
                fields=["organization", "is_enabled"],
                name="campaigns_o_organiz_3bcf3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationemailprovider",
            index=models.Index(
                fields=["organization", "is_primary"],
                name="campaigns_o_organiz_563377_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationemailprovider",
            unique_together={("organization", "provider")},
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["organization", "status"], name="campaigns_c_organiz_a8017f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["organization", "scheduled_at"],
                name="campaigns_c_organiz_004b04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["organization", "is_active", "status"],
                name="campaigns_c_organiz_7addcb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "scheduled_at"], name="campaigns_c_status_4a521f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["organization", "is_active"],
                name="campaigns_a_organiz_a2a61e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["reason_name", "communication_type"],
                name="campaigns_a_reason__1cf5c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["trigger_type", "is_active"],
                name="campaigns_a_trigger_9b24e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["campaign", "is_active"], name="campaigns_a_campaig_f7e6eb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="automationrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("organization", "reason_name", "communication_type"),
                name="unique_org_automation_rule",
            ),
        ),
    ]
