# Generated by Django 5.2.8 on 2026-01-02 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTemplateNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template_updated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the organization has updated their copy of the template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Template Notification",
                "verbose_name_plural": "Organization Template Notifications",
            },
        ),
        migrations.CreateModel(
            name="TemplateApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the requester about the changes",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(blank=True, help_text="Notes from the reviewer"),
                ),
                (
                    "version_before_approval",
                    models.IntegerField(
                        help_text="Template version when submitted for approval"
                    ),
                ),
                (
                    "changes_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of changes made to the template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Approval Request",
                "verbose_name_plural": "Template Approval Requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateUpdateNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_version",
                    models.IntegerField(help_text="Previous version number"),
                ),
                ("new_version", models.IntegerField(help_text="New version number")),
                (
                    "update_summary",
                    models.TextField(
                        help_text="Summary of changes made in this update"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this notification is still active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Update Notification",
                "verbose_name_plural": "Template Update Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("duplicated_at", models.DateTimeField(auto_now_add=True)),
                ("template_name_at_duplication", models.CharField(max_length=255)),
                ("template_version_at_duplication", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Template Usage Log",
                "verbose_name_plural": "Template Usage Logs",
                "ordering": ["-duplicated_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="emailtemplate",
            name="unique_template_per_org",
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPROVED",
                help_text="Approval status for global templates",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When this template was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Platform admin who approved this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="duplicated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who duplicated this template from a global template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicated_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a draft version not yet published",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a global template available to all organizations",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous version of this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_versions",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The global template this was duplicated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="submitted_for_approval_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this template was submitted for approval",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="usage_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of times this global template has been duplicated",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="version",
            field=models.IntegerField(
                default=1, help_text="Version number of this template"
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="version_notes",
            field=models.TextField(
                blank=True, help_text="Changelog or notes about this version"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("EMAIL_VERIFICATION", "Email Verification"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("WELCOME", "Welcome"),
                    ("FOLLOW_UP", "Follow-up"),
                    ("NEWSLETTER", "Newsletter"),
                    ("PROMOTIONAL", "Promotional"),
                    ("ANNOUNCEMENT", "Announcement"),
                    ("EVENT", "Event"),
                    ("INVITATION", "Invitation"),
                    ("REMINDER", "Reminder"),
                    ("NOTIFICATION", "Notification"),
                    ("SUBSCRIPTION_CONFIRMATION", "Subscription Confirmation"),
                    ("SUBSCRIPTION_RENEWAL", "Subscription Renewal"),
                    ("TRANSACTIONAL", "Transactional"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Template category for organization",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this template. Null for global templates.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_templates",
                to="authentication.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["is_global", "approval_status", "is_draft"],
                name="campaigns_e_is_glob_1840c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtemplate",
            index=models.Index(
                fields=["source_template", "organization"],
                name="campaigns_e_source__7a40ba_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("is_global", False)),
                fields=("organization", "template_name"),
                name="unique_template_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_global", False),
                    ("organization__isnull", True),
                    _connector="OR",
                ),
                name="global_templates_no_org",
            ),
        ),
        migrations.AddField(
            model_name="organizationtemplatenotification",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization receiving the notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_notifications",
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationtemplatenotification",
            name="read_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked notification as read",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="read_template_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templateapprovalrequest",
            name="requested_by",
            field=models.ForeignKey(
                help_text="User who submitted the template for approval",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_approval_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templateapprovalrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Platform admin who reviewed the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_template_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templateapprovalrequest",
            name="template",
            field=models.ForeignKey(
                help_text="Template awaiting approval",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="templateupdatenotification",
            name="global_template",
            field=models.ForeignKey(
                help_text="The global template that was updated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_notifications",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="organizationtemplatenotification",
            name="notification",
            field=models.ForeignKey(
                help_text="The template update notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_notifications",
                to="campaigns.templateupdatenotification",
            ),
        ),
        migrations.AddField(
            model_name="templateusagelog",
            name="duplicated_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization-specific template that was created",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_usage_logs",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="templateusagelog",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that duplicated the template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_usage_logs",
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="templateusagelog",
            name="template",
            field=models.ForeignKey(
                help_text="The global template that was used",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_logs",
                to="campaigns.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="templateusagelog",
            name="user",
            field=models.ForeignKey(
                help_text="User who duplicated the template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_duplication_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="templateapprovalrequest",
            index=models.Index(
                fields=["status", "requested_at"], name="campaigns_t_status_8330e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateapprovalrequest",
            index=models.Index(
                fields=["template", "status"], name="campaigns_t_templat_1c0fd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateapprovalrequest",
            index=models.Index(
                fields=["requested_by", "requested_at"],
                name="campaigns_t_request_6cf941_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="templateupdatenotification",
            index=models.Index(
                fields=["global_template", "created_at"],
                name="campaigns_t_global__f13fbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="templateupdatenotification",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="campaigns_t_is_acti_aa4571_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationtemplatenotification",
            index=models.Index(
                fields=["organization", "is_read"],
                name="campaigns_o_organiz_aa10c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationtemplatenotification",
            index=models.Index(
                fields=["notification", "organization"],
                name="campaigns_o_notific_332a4a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationtemplatenotification",
            unique_together={("notification", "organization")},
        ),
        migrations.AddIndex(
            model_name="templateusagelog",
            index=models.Index(
                fields=["organization", "duplicated_at"],
                name="campaigns_t_organiz_9f727f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="templateusagelog",
            index=models.Index(
                fields=["user", "duplicated_at"], name="campaigns_t_user_id_6b90d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateusagelog",
            index=models.Index(
                fields=["template", "organization"],
                name="campaigns_t_templat_463a30_idx",
            ),
        ),
    ]
