# Generated by Django 5.2.8 on 2026-07-30 20:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("AWS_SES", "Amazon SES"),
                    ("SENDGRID", "SendGrid"),
                    ("BREVO", "Brevo (formerly Sendinblue)"),
                    ("SMTP", "Custom SMTP"),
                    ("GMAIL_SMTP", "Gmail SMTP"),
                    ("INTERNAL", "Internal System"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email_address",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("GMAIL", "Gmail"),
                            ("AWS_SES", "Amazon SES"),
                            ("CUSTOM", "Custom SMTP/IMAP"),
                        ],
                        default="GMAIL",
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                (
                    "encrypted_config",
                    models.TextField(help_text="Encrypted account configuration"),
                ),
                ("sync_enabled", models.BooleanField(default=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("SYNCING", "Syncing"),
                            ("ERROR", "Error"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True)),
                ("imap_uid_validity", models.BigIntegerField(blank=True, null=True)),
                (
                    "imap_last_uid",
                    models.BigIntegerField(blank=True, default=0, null=True),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "email_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailbox_accounts",
                        to="campaigns.emailprovider",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Account",
                "verbose_name_plural": "Email Accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MailboxMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        choices=[
                            ("INBOX", "Inbox"),
                            ("SENT", "Sent"),
                            ("DRAFTS", "Drafts"),
                            ("ARCHIVE", "Archive"),
                            ("TRASH", "Trash"),
                            ("SPAM", "Spam"),
                        ],
                        db_index=True,
                        default="INBOX",
                        max_length=20,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(blank=True, db_index=True, max_length=512),
                ),
                (
                    "in_reply_to",
                    models.CharField(blank=True, db_index=True, max_length=512),
                ),
                ("references", models.TextField(blank=True)),
                (
                    "thread_key",
                    models.CharField(blank=True, db_index=True, max_length=512),
                ),
                ("from_address", models.EmailField(db_index=True, max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=255)),
                ("to_addresses", models.JSONField(default=list)),
                ("cc_addresses", models.JSONField(blank=True, default=list)),
                ("bcc_addresses", models.JSONField(blank=True, default=list)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("text_body", models.TextField(blank=True)),
                ("html_body", models.TextField(blank=True)),
                ("snippet", models.CharField(blank=True, max_length=255)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=512),
                ),
                ("imap_uid", models.BigIntegerField(blank=True, null=True)),
                ("raw_headers", models.JSONField(blank=True, default=dict)),
                ("attachments_meta", models.JSONField(blank=True, default=list)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("is_draft", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="campaigns.emailaccount",
                    ),
                ),
                (
                    "delivery_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailbox_messages",
                        to="campaigns.emaildeliverylog",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailbox_messages",
                        to="authentication.organization",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="campaigns.mailboxmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailbox Message",
                "verbose_name_plural": "Mailbox Messages",
                "ordering": ["-received_at", "-sent_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(
                fields=["organization", "account_type"],
                name="campaigns_e_organiz_07426f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(
                fields=["organization", "is_default"],
                name="campaigns_e_organiz_fb2d9e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailaccount",
            constraint=models.UniqueConstraint(
                fields=("organization", "email_address"),
                name="unique_mailbox_email_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="mailboxmessage",
            index=models.Index(
                fields=["organization", "folder", "is_read"],
                name="campaigns_m_organiz_c5eaff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mailboxmessage",
            index=models.Index(
                fields=["account", "folder", "received_at"],
                name="campaigns_m_account_94ea36_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mailboxmessage",
            index=models.Index(
                fields=["account", "message_id"], name="campaigns_m_account_6cead2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailboxmessage",
            index=models.Index(
                fields=["thread_key"], name="campaigns_m_thread__e4b474_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailboxmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("message_id", ""), _negated=True),
                fields=("account", "message_id"),
                name="unique_message_id_per_account",
            ),
        ),
    ]
