# Generated by Django 5.2.8 on 2025-12-29 08:00

from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_unique_tokens(apps, schema_editor):
    """Generate unique subscription tokens for all existing ContactLists."""
    ContactList = apps.get_model('campaigns', 'ContactList')
    for contact_list in ContactList.objects.all():
        contact_list.subscription_token = get_random_string(64)
        contact_list.save(update_fields=['subscription_token'])


def reverse_tokens(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        # Step 1: Add the field without unique constraint, nullable first
        migrations.AddField(
            model_name="contactlist",
            name="subscription_token",
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                editable=False,
                help_text="Unique token for public subscription forms",
            ),
        ),
        # Step 2: Generate unique tokens for existing rows
        migrations.RunPython(generate_unique_tokens, reverse_tokens),
        # Step 3: Make the field non-nullable and unique
        migrations.AlterField(
            model_name="contactlist",
            name="subscription_token",
            field=models.CharField(
                max_length=64,
                unique=True,
                editable=False,
                help_text="Unique token for public subscription forms",
            ),
        ),
    ]
