# Generated by Django 5.2.8 on 2025-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="from_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="from_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="html_content",
            field=models.TextField(blank=True, help_text="HTML email body"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
