# Generated by Django 5.2.8 on 2025-12-17 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "campaigns",
            "0002_alter_campaign_from_email_alter_campaign_from_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="variable_schema",
        ),
    ]
