# Generated by Django 5.2.8 on 2026-01-02 15:45

from django.db import migrations


def set_default_template_values(apps, schema_editor):
    """
    Set default values for existing email templates:
    - is_global = False (all existing templates are organization-specific)
    - version = 1 (start versioning from 1)
    - approval_status = 'APPROVED' (existing templates are already in use)
    - usage_count = 0 (no usage tracking before this feature)
    """
    EmailTemplate = apps.get_model('campaigns', 'EmailTemplate')
    
    # Update all existing templates
    EmailTemplate.objects.all().update(
        is_global=False,
        version=1,
        approval_status='APPROVED',
        usage_count=0,
        is_draft=False,
    )
    
    # Print summary
    count = EmailTemplate.objects.count()
    print(f"✓ Updated {count} existing email templates with default values")


def reverse_migration(apps, schema_editor):
    """
    Reverse operation - not needed as we're just setting defaults
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_add_template_global_and_workflow_features"),
    ]

    operations = [
        migrations.RunPython(set_default_template_values, reverse_migration),
    ]
