# Generated by Django 5.2.8 on 2025-12-29 08:03

import apps.campaigns.models.contact_models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_contactlist_subscription_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlist",
            name="subscription_token",
            field=models.CharField(
                default=apps.campaigns.models.contact_models.generate_subscription_token,
                editable=False,
                help_text="Unique token for public subscription forms",
                max_length=64,
                unique=True,
            ),
        ),
    ]
