# Generated by Django 5.2.8 on 2026-07-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_mailbox_and_gmail_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("GMAIL", "Gmail"),
                    ("AWS_SES", "Amazon SES"),
                    ("SENDGRID", "SendGrid"),
                    ("BREVO", "Brevo"),
                    ("CUSTOM", "Custom SMTP/IMAP"),
                ],
                default="GMAIL",
                max_length=20,
            ),
        ),
    ]
