# Generated by Django 5.2.8 on 2026-08-04 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('campaigns', '0003_sendgrid_brevo_mailbox_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active and usable')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this item is published/visible')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text="Stable slug, e.g. 'free', 'basic'", unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Assigned to new organizations. Only one package can be default.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('contacts_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('campaigns_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('emails_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('emails_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('emails_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('batch_size', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('api_requests_per_minute', models.PositiveIntegerField(blank=True, default=60, null=True)),
                ('max_domains', models.PositiveIntegerField(blank=True, default=0, help_text='Max sending domains an organization may register (NULL = unlimited)', null=True)),
                ('max_sender_emails', models.PositiveIntegerField(blank=True, default=0, help_text='Max sender email addresses across all domains (NULL = unlimited)', null=True)),
                ('custom_domain_allowed', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('bulk_email_allowed', models.BooleanField(default=False)),
                ('ab_testing_allowed', models.BooleanField(default=False)),
                ('org_owned_ses_allowed', models.BooleanField(default=False, help_text="Allow domains provisioned in the organization's own AWS SES account")),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='organizationemailconfiguration',
            name='domain_feature_enabled',
            field=models.BooleanField(default=True, help_text='Platform-admin kill switch for the sending-domains feature'),
        ),
        migrations.AddField(
            model_name='organizationemailconfiguration',
            name='limit_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Sparse per-organization overrides of package limits/flags (override wins)'),
        ),
        migrations.AddField(
            model_name='organizationemailconfiguration',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='campaigns.package'),
        ),
        migrations.CreateModel(
            name='SendingDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active and usable')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this item is published/visible')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('ownership_mode', models.CharField(choices=[('PLATFORM', 'Platform-managed SES account'), ('ORG', "Organization's own SES account")], default='PLATFORM', max_length=20)),
                ('region', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('PENDING_DNS', 'Pending DNS setup'), ('PENDING_VERIFICATION', 'Pending verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification failed'), ('SUSPENDED', 'Suspended by platform admin'), ('DISABLED', 'Disabled')], db_index=True, default='PENDING_DNS', max_length=25)),
                ('previous_status', models.CharField(blank=True, default='', max_length=25)),
                ('dkim_tokens', models.JSONField(blank=True, default=list)),
                ('dns_records', models.JSONField(blank=True, default=list, help_text='Display list of records the org must publish: [{type, name, value, purpose}]')),
                ('mail_from_subdomain', models.CharField(default='mail', max_length=63)),
                ('mail_from_status', models.CharField(blank=True, default='', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('verification_error', models.TextField(blank=True, default='')),
                ('suspension_reason', models.TextField(blank=True, default='')),
                ('legacy', models.BooleanField(default=False, help_text='Migrated from the old OrganizationEmailConfiguration.custom_domain field')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_domains', to='authentication.organization')),
                ('provider', models.ForeignKey(blank=True, help_text='Org-owned AWS SES provider holding the identity (required for ownership_mode=ORG)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sending_domains', to='campaigns.emailprovider')),
            ],
            options={
                'verbose_name': 'Sending Domain',
                'verbose_name_plural': 'Sending Domains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active and usable')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this item is published/visible')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_part', models.CharField(max_length=64)),
                ('email_address', models.EmailField(db_index=True, max_length=320)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended by platform admin')], default='ACTIVE', max_length=20)),
                ('suspension_reason', models.TextField(blank=True, default='')),
                ('mailbox_account', models.OneToOneField(blank=True, help_text='Auto-created inbox account (platform-managed domains only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_email', to='campaigns.emailaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_emails', to='authentication.organization')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_emails', to='campaigns.sendingdomain')),
            ],
            options={
                'verbose_name': 'Sender Email',
                'verbose_name_plural': 'Sender Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('verified', 'Verified'), ('verification_failed', 'Verification failed'), ('suspended', 'Suspended'), ('reactivated', 'Reactivated'), ('deleted', 'Deleted'), ('package_assigned', 'Package assigned'), ('limits_overridden', 'Limits overridden'), ('feature_toggled', 'Feature toggled')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_audit_logs', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Domain Audit Log',
                'verbose_name_plural': 'Domain Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='campaigns_d_organiz_35f9fd_idx'), models.Index(fields=['object_type', 'object_id'], name='campaigns_d_object__be8d19_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sendingdomain',
            index=models.Index(fields=['organization', 'status'], name='campaigns_s_organiz_b9cf2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='sendingdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('domain',), name='uniq_active_sending_domain'),
        ),
        migrations.AddIndex(
            model_name='senderemail',
            index=models.Index(fields=['organization', 'status'], name='campaigns_s_organiz_8dae45_idx'),
        ),
        migrations.AddConstraint(
            model_name='senderemail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email_address',), name='uniq_active_sender_email'),
        ),
    ]
