# Generated by Django 5.2.8 on 2026-01-04 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("campaigns", "0003_set_default_template_values"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active and usable"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is published/visible",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("CAMPAIGN_SENT", "Campaign Sent"),
                            ("CAMPAIGN_SCHEDULED", "Campaign Scheduled"),
                            ("CAMPAIGN_FAILED", "Campaign Failed"),
                            ("CONTACT_ADDED", "Contact Added"),
                            ("CONTACT_SUBSCRIBED", "Contact Subscribed"),
                            ("CONTACT_UNSUBSCRIBED", "Contact Unsubscribed"),
                            ("TEMPLATE_UPDATED", "Template Updated"),
                            ("SYSTEM_UPDATE", "System Update"),
                            ("SYSTEM_ALERT", "System Alert"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (e.g., 'campaign', 'contact')",
                        max_length=50,
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (e.g., stats, links)",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="authentication.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user (if user-specific notification)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_read", "-created_at"],
                        name="campaigns_n_organiz_87b93e_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="campaigns_n_user_id_aa6bd9_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="campaigns_n_notific_bd5ed9_idx",
                    ),
                ],
            },
        ),
    ]
