# Generated by Django 5.2.8 on 2026-01-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0005_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                help_text="Approval status for global templates",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="is_draft",
            field=models.BooleanField(
                default=True,
                help_text="Whether this is a draft version not yet published",
            ),
        ),
    ]
