# Generated by Django 5.2.8 on 2026-01-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_alter_emailtemplate_approval_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True, help_text="When to send the campaign", null=True
            ),
        ),
    ]
