# Generated by Django 5.2.8 on 2025-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="custom_field_schema",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Schema defining custom fields for contact personalization",
            ),
        ),
    ]
