# Generated by Django 5.2.8 on 2026-01-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the organization was deactivated", null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="deactivation_reason",
            field=models.TextField(
                blank=True, help_text="Reason for deactivating the organization"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this organization is active. Inactive organizations cannot login.",
            ),
        ),
    ]
