services:
  app:
    container_name: ecmp-frontend
    image: ghcr.io/musfiqdehan/emailcampaign-frontend:latest
    expose:
      - "3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - ecmp_network

  nginx:
    container_name: frontend-nginx-ecmp
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "${WEB_PORT_FRONTEND:-3002}:80"
    depends_on:
      - app
    networks:
      - ecmp_network

networks:
  ecmp_network:
    name: ecmp_network
    external: true
